# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
    - pull_request
    - push

name: "Continuous Integration"

jobs:
    run:
        name: "Grumphp"
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest, windows-latest, macOS-latest]
                php-versions: ['7.2', '7.3', '7.4']

        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                  fetch-depth: 1

            - name: Install PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring,xdebug

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

            - name: Run Grumphp
              run: vendor/bin/grumphp run --no-ansi -n
              env:
                  STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

            - name: Send PSALM data
              run: vendor/bin/psalm --shepherd --stats
              continue-on-error: true

            - name: Send Scrutinizer data
              run: |
                  wget https://scrutinizer-ci.com/ocular.phar
                  php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
              continue-on-error: true

            - name: Infection score report
              run: |
                  vendor/bin/infection run -j 2
              continue-on-error: true

            - name: PHP Insights report
              run: |
                  rm -rf composer.lock vendor
                  composer require nunomaduro/phpinsights --dev
                  vendor/bin/phpinsights analyse src/ -n
              continue-on-error: true
