# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
    - pull_request
    - push

name: "Continuous Integration"

jobs:
    run:
        name: "Grumphp"
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest, windows-latest, macOS-latest]
                php-versions: ['7.1', '7.2', '7.3', '7.4']
                dependencies: [lowest, highest]

        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                  fetch-depth: 1

            - name: Install PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: xdebug

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}-${{ matrix.dependencies }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer install --no-interaction --no-progress --no-suggest

            - name: "Composer install lowest dependencies"
              if: matrix.dependencies == 'lowest'
              run: composer update --no-interaction --no-progress --no-suggest --prefer-lowest

            - name: Run Grumphp
              run: vendor/bin/grumphp run
              env:
                  STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

            - name: Scrutinizer
              run: vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
